"""init

Revision ID: 2f45e312299a
Revises: 39813a991fd6
Create Date: 2019-04-25 20:36:13.927605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f45e312299a'
down_revision = '39813a991fd6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('street_number', sa.Integer(), nullable=True),
    sa.Column('open_at', mysql.TIME(), nullable=True),
    sa.Column('close_at', mysql.TIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop')
    # ### end Alembic commands ###
