"""init

Revision ID: 39813a991fd6
Revises: 
Create Date: 2019-04-24 21:26:52.159190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39813a991fd6'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
