"""init

Revision ID: 71d5f905e0ec
Revises: 2f45e312299a
Create Date: 2019-04-29 21:12:58.499388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d5f905e0ec'
down_revision = '2f45e312299a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
